# Generated by Django 4.1.3 on 2022-12-24 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be valid', regex='^(0|\\+98)?[1-9]+[\\d]{9}$')]),
        ),
    ]
