# Generated by Django 4.1.3 on 2022-12-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounts',
        ),
        migrations.AddField(
            model_name='product',
            name='discounts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.discount'),
        ),
    ]
