# Generated by Django 4.1.3 on 2023-02-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
